project:
  type: book

book:
  title: "Análisis Exploratorio de Datos"
  subtitle: "Licenciatura en Estadística"
  author: 
    - "Mgs. Lic. Diego Marfetán Molina"
    - "Lic. Iván Millanes"
  date: today
  date-format: long
  search: true
  repo-url: https://github.com/ee-unr/aed
  repo-actions: [edit, issue, source]
  page-footer: "Developed by Diego Marfetán Molina and Ivan Millanes"
  back-to-top-navigation: true
  chapters:
    - index.qmd
    - capitulos/00_info.qmd
    - part: capitulos/01.qmd
      chapters:
        - capitulos/01_teoria_de_la_visualizacion.qmd
        - capitulos/01_buenas_practicas_visualizacion.qmd
        - capitulos/01_introduccion_a_ggplot2.qmd
    - part: capitulos/02.qmd
      chapters:
        - capitulos/02_Rmarkdown.qmd
        - capitulos/02_reportes_parametrizados.qmd
    - part: capitulos/03.qmd
      chapters:
        - capitulos/03_georreferencia.qmd
        - capitulos/03_visualizacion_variables_cualitativas.qmd
    # - part: capitulos/90.qmd
    #   chapters:
    #     - capitulos/90_soluciones_01.qmd
  # appendices:
  #   - capitulos/98_tp.qmd
  #   - capitulos/99_bibliografia.qmd

lang: es

bibliography: capitulos/references.bib

format:
  html:
    theme:
      light: [cosmo, estilo/style.scss]
      dark: [darkly, estilo/style-dark.scss]
    css: webexercises/webex.css
    include-after-body: webexercises/webex.js
    code-link: true
    lightbox: 
      match: auto
      loop: false
    fig-dpi: 300
    fig-show: hold
    fig-align: center
